### PR TITLE
fix: hangs on concurrent layer pulls

### LINKED ISSUE #106: bug: concurrent pulls result in deadlocks
## Description

Pulling the same package at the same time will result in a deadlock around the mutex.

## Steps to Reproduce

1. Start the pull of two of the same packages at once through `registry.pull`

## Expected Behavior

* The package is downloaded successfully

### PR DESCRIPTION
**Pull request by Noxsios**
Fixes #106

### CODE REVIEW

File: src/main/kotlin/com/defenseunicorns/koci/Layout.kt [hunk 1]
```diff
@@ -192,6 +192,10 @@ class Layout private constructor(
     @OptIn(ExperimentalSerializationApi::class)
     @Suppress("detekt:LongMethod", "detekt:CyclomaticComplexMethod")
     suspend fun remove(descriptor: Descriptor): Result<Boolean> = runCatching {
```
Comment (Racer159) [inline src/main/kotlin/com/defenseunicorns/koci/Layout.kt:194]: remove should lock the mutex as well - a download could try to start during a removal

Comment (Noxsios) [reply src/main/kotlin/com/defenseunicorns/koci/Layout.kt:194]: i placed a guard for this, but downloads only currently track at the layer level, there is no "lock" for a manifest/index

trying to think of the scenario where this could cause a bad state to occur

Comment (Racer159) [reply src/main/kotlin/com/defenseunicorns/koci/Layout.kt:194]: The main issue is that this implementation relies on filesystem implementations of file descriptors/handles to handle concurrency between `push` and `remove` which could result in different behavior on different systems depending on how they implemented that functionality - because a `file.delete()` and a `FileOutputStream().use` could be called simultaneously (since the guard only guards `remove`s entrypoint) this would fallback onto that machine's implementation for deconfliction.  A more robust approach would mutex both ends of that.
